//
//  DaliyData.swift
//  HFUTXhining
//
//  Created by   chironyf on 2017/8/18.
//  Copyright © 2017年 chironyf. All rights reserved.
//

import Foundation

let daliyData = [DaliyTableViewCellModel(userIdNew: "2015", userNameNew: "jods", userHeadImageURLNew: "nil", userPostTimeNew: "11:23", userTypeNew: UserType.normalUser, userPostIdNew: "2563", userPostContentURLNew: "fhdsuiafyueiwqhfkjdshajkfdsahfjksdahfjksdahfjkhsdajkhfkuwehafuiehawfkjdsafbjsda", userLikeAmountNew: 99, userCommentAmountNew: 99, userShareAmountNew: 99, userCommentContentURLNew: "www.baidu.com", userPostTypeNew: UserPostType.originPost, userForwardAmountNew: 100), DaliyTableViewCellModel(userIdNew: "2015", userNameNew: "jods", userHeadImageURLNew: "nil", userPostTimeNew: "11:23", userTypeNew: UserType.normalUser, userPostIdNew: "2563", userPostContentURLNew: "fhdsuiafyueiwqhfkjdshajkfdsahfjksdahfjksdahfjkhsdajkhfkuwehafuiehawfkjdsafbjsda", userLikeAmountNew: 99, userCommentAmountNew: 99, userShareAmountNew: 99, userCommentContentURLNew: "www.baidu.com", userPostTypeNew: UserPostType.originPost, userForwardAmountNew: 100), DaliyTableViewCellModel(userIdNew: "2015", userNameNew: "jods", userHeadImageURLNew: "nil", userPostTimeNew: "11:23", userTypeNew: UserType.normalUser, userPostIdNew: "2563", userPostContentURLNew: "fhdsuiafyueiwqhfkjdshajkfdsahfjksdahfjksdahfjkhsdajkhfkuwehafuiehawfkjdsafbjsda", userLikeAmountNew: 99, userCommentAmountNew: 99, userShareAmountNew: 99, userCommentContentURLNew: "www.baidu.com", userPostTypeNew: UserPostType.originPost, userForwardAmountNew: 100), DaliyTableViewCellModel(userIdNew: "2015", userNameNew: "jods", userHeadImageURLNew: "nil", userPostTimeNew: "11:23", userTypeNew: UserType.normalUser, userPostIdNew: "2563", userPostContentURLNew: "fhdsuiafyueiwqhfkjdshajkfdsahfjksdahfjksdahfjkhsdajkhfkuwehafuiehawfkjdsafbjsda", userLikeAmountNew: 99, userCommentAmountNew: 99, userShareAmountNew: 99, userCommentContentURLNew: "www.baidu.com", userPostTypeNew: UserPostType.originPost, userForwardAmountNew: 100), DaliyTableViewCellModel(userIdNew: "2015", userNameNew: "jods", userHeadImageURLNew: "nil", userPostTimeNew: "11:23", userTypeNew: UserType.normalUser, userPostIdNew: "2563", userPostContentURLNew: "fhdsuiafyueiwqhfkjdshajkfdsahfjksdahfjksdahfjkhsdajkhfkuwehafuiehawfkjdsafbjsda", userLikeAmountNew: 99, userCommentAmountNew: 99, userShareAmountNew: 99, userCommentContentURLNew: "www.baidu.com", userPostTypeNew: UserPostType.originPost, userForwardAmountNew: 100), DaliyTableViewCellModel(userIdNew: "2015", userNameNew: "jods", userHeadImageURLNew: "nil", userPostTimeNew: "11:23", userTypeNew: UserType.normalUser, userPostIdNew: "2563", userPostContentURLNew: "fhdsuiafyueiwqhfkjdshajkfdsahfjksdahfjksdahfjkhsdajkhfkuwehafuiehawfkjdsafbjsda", userLikeAmountNew: 99, userCommentAmountNew: 99, userShareAmountNew: 99, userCommentContentURLNew: "www.baidu.com", userPostTypeNew: UserPostType.originPost, userForwardAmountNew: 100)]
